pridana specifikacia / katalog poziadaviek
TIS2016/Sportovy-klub pull request #11
Opened 2016-10-10 19:36 UTC by michalpuskel

prosim vyexportujte niekto pdf z toho tex suboru mam rozbity tex momentalne... iba som nieco upravil...

2016-10-10 19:42 UTC, JaroFuska reviewed
nesúlad vo vstupných podmienkách pri definovaní funkcionality. pri užívateľovi je všade vstupná podmienka byť prihlásený a pri trénerovi a adminovi už nie je.
- existencia príspevku a existencia skupiny pri trénerovi a adminovi tam je tiež nesúlad.

Navrhujem vymazať vstupné podmienky typu existencia skupiny, existencia...

2016-10-10 19:45 UTC, JaroFuska requested changes
prosím pozmeniť pred mergovaním

2016-10-11 11:13 UTC, slama6 reviewed
Malo by to byt upravene v tex dokumente.

2016-10-17 18:39 UTC, michalpuskel commented
toto uz zavreme lebo Tomas uz vyexportoval aj upravil katalog

2016-10-17 18:39 UTC, closed without merging